//
//  SNRendererHostReceiver.swift
//  SolidNative
//
//  Created by Imran Shitta-Bey on 1/8/25.

import SNLib
import UIKit


@objc public class HostReceiver: NSObject, SNRendererHostReceiverProtocol {
    public func doesNodeRequireMeasuring(_ nodeType: String?) -> Bool {
        let doesRequire = viewTypeRegistry[nodeType!]!.doesRequireMeasuring
        return doesRequire
    }
    
    public func getDeviceScreenSize() -> SNRendererSize? {
        // Get the width and height of the device screen
        let screenWidth = UIScreen.main.bounds.width
        let screenHeight = UIScreen.main.bounds.height
        return SNRendererSize(Float(screenWidth), height: Float(screenHeight))
    }
    
    public func isTextElement(byNodeId nodeId: String?) -> Bool {
        viewWrapperRegistry[nodeId!]!.solidNativeViewType.isTextElement
    }
    
    public func isTextElement(byNodeType nodeType: String?) -> Bool {
        viewTypeRegistry[nodeType!]!.isTextElement
    }
    
    public func measureNode(_ nodeId: String?, proposedSize: SNRendererSize?, sizeMode: SNRendererSizeMode?) -> SNRendererSize? {
        let node = viewWrapperRegistry[nodeId!]!
        let size = node.solidNativeView!.measureNode(nodeId!)
        print("Size: ", size.height)
        return size
    }
    
    public func onChildrenChange(_ nodeId: String?, nodeIds: SNCoreStringArray?) {
        print("Node Ids: \(String(describing: nodeIds?.length()))")
        viewWrapperRegistry[nodeId!]!.children = nodeIds!
    }
    
    public func onLayoutChange(_ nodeId: String?, layoutMetrics: SNRendererLayoutMetrics?) {
        print("Layout Metrics: ", layoutMetrics?.width, layoutMetrics?.height)
        viewWrapperRegistry[nodeId!]!.layoutMetrics = layoutMetrics!
    }
    
    public func onNodeCreated(_ nodeId: String?, nodeType: String?) {
        let viewType = viewTypeRegistry[nodeType!]!
        
        viewWrapperRegistry[nodeId!] = SolidNativeViewWrapper(viewType: viewType, hostReceiver: self)
    }
    
    public func onNodeRemoved(_ nodeId: String?) {
        viewWrapperRegistry.removeValue(forKey: nodeId!)
        // May want to call some sort of lifecycle method
    }
    
    public func onNodeTextDescriptorsChange(_ nodeId: String?, textDescriptors: SNRendererTextDescriptorArray?) {
        viewWrapperRegistry[nodeId!]!.textDescriptor = textDescriptors
    }
    
    public func onPropUpdated(_ nodeId: String?, key: String?, value: SNRendererJSValue?) {
        viewWrapperRegistry[nodeId!]!.props[key!] = value!
    }
    
    public func onUpdateRevisionCount(_ nodeId: String?) {
        viewWrapperRegistry[nodeId!]!.updateRevisionCount()
    }
    
    // TODO: This needs to be autogenerated
    let viewTypeRegistry: [String: any SolidNativeView.Type] = [
        SNView.name: SNView.self,
        SNText.name: SNText.self
    ]
    
    var viewWrapperRegistry: [String: SolidNativeViewWrapper] = [:]
    
    var rootNodeId: String?
    
    func getRootNode() -> SolidNativeViewWrapper {
        viewWrapperRegistry[rootNodeId!]!
    }
}
