//
//  SolidNativeCore.swift
//  SolidNative
//
//  Created by Imran Shitta-Bey on 6/20/24.
//

import Foundation
import Snmobile
import UIKit

var SharedSolidNativeCore: SolidNativeCore!

@objc public class SwiftPrinter: NSObject, SNSnmobileMobilePrinterProtocol {
    public func write(toMobilePrinter input: String?) {
        print(input ?? "")
    }
}


@objc public class SolidNativeCore: NSObject, SNSnmobileHostReceiverProtocol {
    public func onNodeTextDescriptorsChange(_ nodeId: String?, textDescriptors: SNSnmobileTextDescriptorArray?) {}

    override public init() {
        super.init()
        if SharedSolidNativeCore == nil {
            SharedSolidNativeCore = self
        }
    }
    
    var snmobile: SNSnmobileSolidNativeMobile!
    
    var viewWrapperRegistry: [String: SolidNativeViewWrapper] = [:]
    
    // TODO: This needs to be autogenerated
    let viewTypeRegistry: [String: any SolidNativeView.Type] = [
        SNView.name: SNView.self,
        SNText.name: SNText.self
    ]
    
    var rootNodeId: String?
    
    func start(jsUrl: String) throws {
        snmobile = SNSnmobileSolidNativeMobile(self)!

        snmobile.setPrinter(SwiftPrinter())
        
        let nodeId = snmobile.createRootNode("sn_view")
        
        viewWrapperRegistry[nodeId] = SolidNativeViewWrapper(viewType: SNView.self)
        
        rootNodeId = nodeId
        
        snmobile.registerModules()
        
        try snmobile.runJs(fromServer: jsUrl)
    }
    
    func getRootNode() -> SolidNativeViewWrapper {
        viewWrapperRegistry[rootNodeId!]!
    }
}

// Conform to Protocol
public extension SolidNativeCore {
    func doesNodeRequireMeasuring(_ nodeType: String?) -> Bool {
        let doesRequire = viewTypeRegistry[nodeType!]!.doesRequireMeasuring
        return doesRequire
    }
    
    func getDeviceScreenSize() -> SNSnmobileSize? {
        // Get the width and height of the device screen
        let screenWidth = UIScreen.main.bounds.width
        let screenHeight = UIScreen.main.bounds.height
        return SNSnmobileSize(Float(screenWidth), height: Float(screenHeight))
    }
    
    func isTextElementByNodeId(_ nodeId: String?) -> Bool {
        viewWrapperRegistry[nodeId!]!.solidNativeViewType.isTextElement
    }
    
    func isTextElement(byNodeType nodeType: String?) -> Bool {
        viewTypeRegistry[nodeType!]!.isTextElement
    }
    
    // TODO: Impliment
    func measureNode(_ nodeId: String?, proposedSize: SNSnmobileSize?, sizeMode: SNSnmobileSizeMode?) -> SNSnmobileSize? {
        let node = viewWrapperRegistry[nodeId!]!
        let size = node.solidNativeViewType.measureNode(nodeId!)
        print("Size: ", size.height)
        return size
    }
    
    func onChildrenChange(_ nodeId: String?, nodeIds: SNSnmobileStringArray?) {
        print("Node Ids: \(String(describing: nodeIds?.length()))")
        viewWrapperRegistry[nodeId!]!.children = nodeIds!
    }
    
    func onLayoutChange(_ nodeId: String?, layoutMetrics: SNSnmobileLayoutMetrics?) {
        print("Layout Metrics: ", layoutMetrics?.width, layoutMetrics?.height)
        viewWrapperRegistry[nodeId!]!.layoutMetrics = layoutMetrics!
    }
    
    func onNodeCreated(_ nodeId: String?, nodeType: String?) {
        let viewType = viewTypeRegistry[nodeType!]!
        
        viewWrapperRegistry[nodeId!] = SolidNativeViewWrapper(viewType: viewType)
    }
    
    // TODO: Impliment me!
    func onNodeRemoved(_ nodeId: String?) {
        // let viewType = viewTypeRegistry[nodeType!]!
        
        // viewWrapperRegistry[nodeId!] = SolidNativeViewWrapper(viewType: viewType)
    }
    
    func onPropUpdated(_ nodeId: String?, key: String?, value: SNSnmobileJSValue?) {
        // print("For node \(nodeId) key changed! \(key)")
        viewWrapperRegistry[nodeId!]!.props[key!] = value!
    }
    
    func onUpdateRevisionCount(_ nodeId: String?) {
        viewWrapperRegistry[nodeId!]!.updateRevisionCount()
    }
}
