name: Validate Website

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build [Gatsby]
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-website

      - name: yarn build
        run: yarn build
        working-directory: website

  build_next:
    name: Build [Docusaurus]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-js

      - name: Restore emsdk
        uses: ./.github/actions/cache-emsdk

      - name: Build Website
        run: yarn build
        working-directory: website-next

  typecheck:
    name: Typecheck [Docusaurus]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup
        uses: ./.github/actions/setup-js

      - name: yarn tsc
        run: yarn tsc
        working-directory: website-next
