name: Setup Apple envirionment

runs:
  using: "composite"
  steps:
    # TODO: This and Ruby should be versioned
    - name: Install Cocoapods
      shell: bash
      run: sudo gem install cocoapods

    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: 14.3.1
